import math
import turtle
x, y = map(int, input("Ingrese las coordenadas del centro del círculo (x y): ").split())
r = int(input("Ingrese el radio del círculo: "))
screen = turtle.Screen()
screen.bgcolor("white")
t = turtle.Turtle()
t.pencolor("red")
t.pensize(2)
t.penup()
t.goto(x, y - r)
t.pendown()
t.circle(r)
area = math.pi * (r ** 2)
t.penup()
t.goto(x, y)
t.pencolor("blue")
t.write(f"{area:.2f}", align="center", font=("Arial", 12, "normal"))
t.hideturtle()
screen.exitonclick()
input("Presiona Enter para salir...")